## Makefile for ProBoard v1.xx

## Caution!! The standard Borland C++ library has to be changed before compiling
## ProBoard v1.30 - The __NFILE__ macro in the file _nfile.h should be changed to
## 100. The files FILES.C and FILES2.C in the RTL\CLIB directory should be
## recompiled using all memory models, and updated in C?.LIB

BCDIR   = C:\BORLANDC
LIBDIR  = $(BCDIR)\LIB
PB_LIB  = ..\PBLIB

###################################################################################
# You shouldn't have to touch things under here

MODEL   = LARGE
OVERLAY = 1

OBJS = chat.obj      shell.obj     login.obj     pbuser.obj    readmsg.obj  \
       mailchk.obj   msg.obj       zip.obj      \
       writemsg.obj  tops.obj      forward.obj   replymsg.obj  timestat.obj \
       msgdel.obj    combined.obj  question.obj  aka.obj       qscanmsg.obj \
       showmsg.obj   scanmsg.obj   version.obj   rawdir.obj    msged.obj    \
       dl.obj        viewfile.obj  lastcall.obj  desqview.obj  stacking.obj \
       cleanup.obj   sysopkey.obj  msgfind.obj   binlog.obj    protocol.obj \
       listfile.obj  ul.obj        tag.obj       sellang.obj   proboard.obj \
       nodelist.obj  online.obj    msgmove.obj   cdrom.obj     regis.obj    \
       mchat.obj     setarea.obj   usered.obj    deckey.obj    music.obj    \
       gif.obj       msgexprt.obj  help.obj      ega.obj       event.obj    \
       filearea.obj  msgarea.obj   timelog.obj   wordwrap.obj  showans.obj  \
       userset.obj   usage.obj     loadpex.obj   image.obj     postmsg.obj  \
       pexcall.obj   strvars.obj   userwin.obj   bulletin.obj  modem.obj    \
       execheck.obj  language.obj  fuzzy.obj     terminal.obj  squish.obj   \
       hudson.obj msgbase.obj mark.obj rip.obj jam.obj inpdate.obj tag_rw.obj

OBJS_NO = exec.obj io.obj fossil.obj menu.obj misc.obj timer.obj


OVLOBJS = $(OBJS,Nexec\.obj,Nio\.obj,Nfossil\.obj,Ntimer\.obj,Nmisc\.obj)
AFLAGS  = /o /mx /dMEM_MOD=$(MODEL)

LIBS    = $(PB_LIB)\pblib_L.lib $(PB_LIB)\tslib_l.lib $(PB_LIB)\SQSH_L.LIB $(PB_LIB)\TSWIN_L.LIB
TSLIB   = 1
TSWIN   = 1
SQUISH  = 1
PBLIB   = 1

.cpp.obj:
       $(CC) @mc.cfg $(CPPFLAGS) /c $&.cpp
.c.obj:
       $(CC) @mc.cfg $(CFLAGS) /c $&.c

#----------------------------------------------------------------------------#

all: proboard.exe

clean:
	-del *.rsp
	-del proboard.exe

pblibs.rsp: $(LIBS)
		-del $<
	    &echo $?+ >> $<
	    echo CL.LIB+ >> $<
	    echo OVERLAY.LIB >> $<

pbobjsno.rsp: $(OBJS_NO)
		-del $<
	    &echo $?+ >> $<

pbobjs.rsp: $(OBJS) $(OBJS_NO)
		-del $<
	    &echo $?+ >> $<
	    #type pbobjsno.rsp >> $<
	    echo c0L.obj >> $<

ProBoard.exe: pblibs.rsp pbobjs.rsp
       tlink /c @pbobjs.rsp,$<,,@pblibs.rsp /L$(LIBDIR)
       #bcc -ml -L\PBLIB -L$(LIBDIR) $(OBJS) $(LIBS)
