!include ..\..\common.mk

OBJS = error.obj init.obj keyboard.obj misc.obj popmenu.obj \
       rectang.obj scan.obj select.obj viewlist.obj window.obj pws_asm.obj \
       form.obj restore.obj editwin.obj gauge.obj savebuf.obj msgbox.obj \
       selbox.obj tsw_asm.obj

all: mc.cfg ..\TSWIN_$(EXT).LIB

..\TSWIN_$(EXT).LIB: $(OBJS)
   -erase $@
   &tlib $@ +$?

 !include ..\..\mc.mk
