## Makefile for ProCFG

!include ..\common.mk

PB_LIB   = ..\LIBS

OBJS = procfg.obj editaka.obj editlim.obj editmac.obj \
       editmenu.obj editarea.obj editpb.obj editprot.obj editsys.obj \
       edituser.obj events.obj editpvt.obj language.obj sel_lang.obj \
       extsel.obj flags.obj promisc.obj editvtpl.obj template.obj     \
       editgrp.obj editlcol.obj editnode.obj area.obj misc.obj


.cpp.obj: 
  $(CC) @mc.cfg $(CPPFLAGS) -I. -I..\LIBS\TH -I..\LIBS\PB  -Yo -c $<

OVERLAY = 1

#OVLOBJS = $(OBJS,Ntemplate\.obj,Nedituser\.obj,Narea\.obj)
LIBS = $(PB_LIB)\proboard.lib $(PB_LIB)\thehouse.lib \
      $(PB_LIB)\TSLIB_L.LIB $(PB_LIB)\TSWIN_L.LIB \
      $(PB_LIB)\PBLIB_L.LIB

CFLAGS = -I$(PB_LIB)\pb -I$(PB_LIB)\th

all: mc.cfg ProCFG.EXE

ProCFG.exe: $(OBJS) $(LIBS)
	$(TLINK) /c /x /L$(LIBDIR) @&&|
	c0l  $(OBJS)
$*
nul
emu mathl overlay cl $(LIBS) 
|

clean:
  -@del *.obj
  -@del mc.cfg
  -@del procfg.exe


!include ../mc.mk
