## Makefile for ProCFG

!include ..\common.mk

PB_LIB   = ..\LIBS

OBJS = procfg.obj editaka.obj editlim.obj editmac.obj \
       editmenu.obj editarea.obj editpb.obj editprot.obj editsys.obj \
       edituser.obj events.obj editpvt.obj language.obj sel_lang.obj \
       extsel.obj flags.obj promisc.obj editvtpl.obj template.obj     \
       editgrp.obj editlcol.obj editnode.obj area.obj misc.obj

OVERLAY = 1

#OVLOBJS = $(OBJS,Ntemplate\.obj,Nedituser\.obj,Narea\.obj)
LIBS = $(PB_LIB)\pb\proboard.lib $(PB_LIB)\th\thehouse.lib

CFLAGS = -I$(PB_LIB)\pb -I$(PB_LIB)\th

all: mc.cfg ProCFG.EXE

ProCFG.exe: $(OBJS) $(LIBS)
	$(TLINK) /c /x /L$(LIBDIR) @&&|
	c0l  $(OBJS)
$*
nul
emu mathl overlay cl $(LIBS) 
|


!include ../mc.mk
